Core 485 throw an error upon startup, if smart agent account config is invalid
evannetwork/edge-server-seed pull request #6
Opened 2019-12-05 13:49 UTC by OmairLiaquatAli

2019-12-09 07:41 UTC, wulfraem requested changes

2019-12-09 07:41 UTC, wulfraem commented on lib/smart-agent.js
> +    console.dir(this.config)
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +//const dirtyChai = require('dirty-chai')
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    console.log(test)
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    console.log(test)
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    // add temporary account to api
```suggestion
    // remove account from config (if present)
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    //api.config.ethAccounts['0x15B10D6521D17a205eaC67b41770c7F447431d89'] = ''
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    console.log(test)
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    console.log(test)
```suggestion
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +          ethAccount:'0x0000000000000000000000000000000000000000',
```suggestion
          ethAccount:'0x0000000000000000000000000000000000000000'
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +        });
```suggestion
        })
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +      ethAccount: '0x15B10D6521D17a205eaC67b41770c7F447431d89',
```suggestion
      ethAccount: '0x15B10D6521D17a205eaC67b41770c7F447431d89'
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    });
```suggestion
    })
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +      ethAccount: '0x15B10D6521D17a205eaC67b41770c7F447431d89',
```suggestion
      ethAccount: '0x15B10D6521D17a205eaC67b41770c7F447431d89'
```

2019-12-09 07:41 UTC, wulfraem commented on test/startupChecks.js
> +    });
```suggestion
    })
```

2019-12-09 07:57 UTC, Tschuck requested changes

2019-12-09 07:57 UTC, Tschuck commented on lib/smart-agent.js
> +    if(!this.config.ethAccount){
```suggestion
    if (!this.config.ethAccount) {
```

2019-12-09 07:57 UTC, Tschuck commented on lib/smart-agent.js
> +    if(this.config.ethAccount === '0x0000000000000000000000000000000000000000'){
```suggestion
    if (this.config.ethAccount === '0x0000000000000000000000000000000000000000') {
```

2019-12-09 07:57 UTC, Tschuck commented on lib/smart-agent.js
> +    if(!api.config.ethAccounts[this.config.ethAccount]){
```suggestion
    if (!api.config.ethAccounts[this.config.ethAccount]) {
```

2019-12-09 15:32 UTC, wulfraem approved these changes

2019-12-09 15:34 UTC, Tschuck submitted a review, later dismissed

2019-12-09 15:34 UTC, Tschuck commented on test/startupChecks.js
> +          ethAccount:'0x0000000000000000000000000000000000000000'
```suggestion
      ethAccount:'0x0000000000000000000000000000000000000000'
```

2019-12-09 15:34 UTC, Tschuck commented on test/startupChecks.js
> +        })
```suggestion
    })
```

2019-12-11 07:44 UTC, karladler commented on test/startupChecks.js
> +    await expect(test.initialize()).to.not.be.rejected
this looks like more correct english, but I didn't tested it 

```suggestion
    await expect(test.initialize()).not.to.be.rejected 
```

2019-12-18 15:10 UTC, S3bb1 approved these changes

2019-12-18 15:13 UTC, merged